import type { NormRect } from './stamps.js';

/** How the user produced the signature image:
 *  - 'drawn': hand-drawn on a canvas in the renderer.
 *  - 'typed': typed name rendered with a handwriting font in the renderer.
 *  - 'image': imported from a PNG/JPG on disk.
 * The disk representation is always a raster image; this tag just preserves
 * provenance for the UI (badge, default sizing, etc.). */
export type SignatureKind = 'drawn' | 'typed' | 'image';

export type SignatureExt = 'png' | 'jpg' | 'jpeg';

export interface Signature {
  id: string;
  kind: SignatureKind;
  /** User-visible label. Falls back to the source filename for 'image'. */
  label: string;
  ext: SignatureExt;
  /** ISO timestamp. */
  createdAt: string;
}

/** Bytes generated by a renderer-side canvas (drawn / typed). Always PNG. */
export interface CreateSignatureFromBytesInput {
  kind: 'drawn' | 'typed';
  label: string;
  /** Raw PNG bytes from the canvas. */
  bytes: Uint8Array;
}

export interface ApplySignatureInput {
  filePath: string;
  pageIndex: number;
  signatureId: string;
  rect: NormRect;
  password?: string;
}

export interface ApplySignatureResult {
  applied: boolean;
}

// ---------------------------------------------------------------------------
// Fase 2: inspection of existing /Sig fields in a PDF
// ---------------------------------------------------------------------------

/** Chain-of-trust verdict for the signer cert. Independent of integrity:
 * a CMS that's cryptographically valid still earns no trust if its cert
 * doesn't chain to a recognized root. */
export type SignatureTrustStatus =
  /** Chain verifies against a Mozilla-trusted root CA. */
  | 'trusted'
  /** Subject DN == issuer DN. No third party vouches for this identity. */
  | 'self-signed'
  /** Chain doesn't reach a trusted root (or the chain is incomplete). */
  | 'untrusted'
  /** Couldn't compute (parse failure / no cert in CMS). */
  | 'unknown';

/** Status of an existing signature relative to the document's current bytes. */
export type SignatureIntegrityStatus =
  /** Hash of the byte-range matches the digest in the CMS — document hasn't
   * been altered since this signature was applied. */
  | 'untampered'
  /** The byte-range stops before the end of the file, meaning content was
   * appended after the signature was applied (an "incremental update").
   * The signature itself is still cryptographically valid for the range it
   * covers; the warning is that the trailing bytes are unsigned. */
  | 'modified-after'
  /** Hash mismatch: the bytes inside the byte-range have changed since
   * signing. The signature is broken. */
  | 'invalid'
  /** Couldn't parse the field or its CMS payload. */
  | 'unknown';

export interface ExistingSignatureInfo {
  /** /T (field name) from the AcroForm field. Falls back to "Signature{n}". */
  fieldName: string;
  /** /SubFilter value: adbe.pkcs7.detached, ETSI.CAdES.detached, ETSI.RFC3161, ... */
  subFilter: string;
  /** CN (or first available DN component) of the signer cert. */
  signerName: string | null;
  /** CN of the cert issuer. Equals signerName when self-signed; null when
   * the parser couldn't reach the cert. */
  issuerCN: string | null;
  /** True when subject DN == issuer DN. Self-signed certs prove only what
   * their holder asserts — there's no third party vouching for the identity
   * — so the UI should make this distinction explicit. */
  isSelfSigned: boolean;
  /** Signing time. Prefers the CMS signed attribute; falls back to /M. ISO string. */
  signedAt: string | null;
  /** /Reason from the signature dict, if present. */
  reason?: string;
  /** /Location from the signature dict, if present. */
  location?: string;
  /** Integrity verdict — see SignatureIntegrityStatus for semantics. */
  integrity: SignatureIntegrityStatus;
  /** True if this signature includes a DocMDP /TransformParams entry — i.e.
   * it's a certification signature, not a plain approval signature. */
  isCertification: boolean;
  // -------------------------------------------------------------------------
  // Temporal validity — cert's own NotBefore/NotAfter window. Independent
  // from integrity: a cert can be expired today yet have been valid at the
  // time of signing, which keeps the historical signature meaningful (the
  // PAdES long-term validation story).
  // -------------------------------------------------------------------------
  /** Cert's notBefore (ISO). */
  validFrom: string | null;
  /** Cert's notAfter (ISO). */
  validTo: string | null;
  /** `now` is within [notBefore, notAfter]. Null when the dates are missing. */
  validNow: boolean | null;
  /** Signing time was within [notBefore, notAfter]. Null when either bound or
   * signedAt was missing. THIS is what matters for whether the historical
   * signature was valid — `validNow` only matters if you plan to KEEP using
   * this cert to sign new things. */
  validAtSigning: boolean | null;
  /** Cert's notAfter is in the past today. Null when notAfter was missing. */
  expiredNow: boolean | null;
  // -------------------------------------------------------------------------
  // Trust dimension — chain-of-trust verdict against Mozilla's root bundle.
  // -------------------------------------------------------------------------
  trustStatus: SignatureTrustStatus;
  /** CN of the trusted root when trustStatus === 'trusted'. */
  trustedRootCN: string | null;
  // -------------------------------------------------------------------------
  // Revocation (OCSP) — independent of integrity AND trust. A cert can be
  // technically valid (chain ok, not expired) yet revoked by the CA, e.g.
  // after a private-key compromise.
  // -------------------------------------------------------------------------
  /** Revocation verdict from the OCSP responder:
   *   - 'good': responder confirmed the cert is in good standing
   *   - 'revoked': responder confirmed revocation (with optional timestamp)
   *   - 'unknown': responder didn't know about the cert
   *   - 'unchecked': we couldn't reach the responder (no AIA URL, network
   *     failure, no issuer cert in the CMS, etc.). Distinct from 'unknown'
   *     because it's our limitation, not the responder's verdict. */
  revocationStatus: 'good' | 'revoked' | 'unknown' | 'unchecked';
  /** ISO timestamp the cert was revoked, if revocationStatus === 'revoked'. */
  revokedAt?: string;
  /** RFC 5280 revocation reason code name, if the responder included it. */
  revocationReason?: string;
}

export interface InspectSignaturesResult {
  signatures: ExistingSignatureInfo[];
}

// ---------------------------------------------------------------------------
// Fase 3: cryptographic (PKCS#7 / CMS) digital signing
// ---------------------------------------------------------------------------

/** Inputs for a cryptographic sign operation. */
export interface SignDigitalInput {
  filePath: string;
  /** Id of a stored Certificate. */
  certId: string;
  /** Passphrase for the cert's PKCS#12 — never persisted; the user must
   * re-supply it on every signing operation. */
  certPassword: string;
  /** PDF password if the PDF is encrypted (same convention as applyStamp). */
  password?: string;
  /** Optional /Reason field embedded in the signature dict. */
  reason?: string;
  /** Optional /Location field. */
  location?: string;
  /** Optional /ContactInfo field. */
  contactInfo?: string;
  /** Optional id of a saved visual signature image to use as the widget's
   * visual appearance (/AP /N). If omitted, the signature is invisible. */
  visualSignatureId?: string;
  /** Page index for the visual appearance. Ignored when invisible. */
  pageIndex?: number;
  /** Normalized rect for the visual appearance. Ignored when invisible. */
  rect?: NormRect;
  /** Optional RFC 3161 TSA URL. When set, the signer requests a trusted
   * timestamp and embeds it as an unsignedAttribute in the SignerInfo,
   * upgrading the signature to PAdES-T (still verifiable past cert expiry). */
  tsaUrl?: string;
  /** PAdES-LT: when true, the signer pre-fetches an OCSP response for the
   * signer cert and embeds it (with the full cert chain) into the
   * document's /DSS. Verifiers can then validate the signature OFFLINE
   * for the long term — no dependency on the OCSP responder being live. */
  embedRevocationInfo?: boolean;
}

export interface SignDigitalResult {
  applied: boolean;
}
