import type { NormRect } from './stamps.js';

/** How the user produced the signature image:
 *  - 'drawn': hand-drawn on a canvas in the renderer.
 *  - 'typed': typed name rendered with a handwriting font in the renderer.
 *  - 'image': imported from a PNG/JPG on disk.
 * The disk representation is always a raster image; this tag just preserves
 * provenance for the UI (badge, default sizing, etc.). */
export type SignatureKind = 'drawn' | 'typed' | 'image';

export type SignatureExt = 'png' | 'jpg' | 'jpeg';

export interface Signature {
  id: string;
  kind: SignatureKind;
  /** User-visible label. Falls back to the source filename for 'image'. */
  label: string;
  ext: SignatureExt;
  /** ISO timestamp. */
  createdAt: string;
}

/** Bytes generated by a renderer-side canvas (drawn / typed). Always PNG. */
export interface CreateSignatureFromBytesInput {
  kind: 'drawn' | 'typed';
  label: string;
  /** Raw PNG bytes from the canvas. */
  bytes: Uint8Array;
}

export interface ApplySignatureInput {
  filePath: string;
  pageIndex: number;
  signatureId: string;
  rect: NormRect;
  password?: string;
}

export interface ApplySignatureResult {
  applied: boolean;
}

// ---------------------------------------------------------------------------
// Fase 2: inspection of existing /Sig fields in a PDF
// ---------------------------------------------------------------------------

/** Status of an existing signature relative to the document's current bytes. */
export type SignatureIntegrityStatus =
  /** Hash of the byte-range matches the digest in the CMS — document hasn't
   * been altered since this signature was applied. */
  | 'untampered'
  /** The byte-range stops before the end of the file, meaning content was
   * appended after the signature was applied (an "incremental update").
   * The signature itself is still cryptographically valid for the range it
   * covers; the warning is that the trailing bytes are unsigned. */
  | 'modified-after'
  /** Hash mismatch: the bytes inside the byte-range have changed since
   * signing. The signature is broken. */
  | 'invalid'
  /** Couldn't parse the field or its CMS payload. */
  | 'unknown';

export interface ExistingSignatureInfo {
  /** /T (field name) from the AcroForm field. Falls back to "Signature{n}". */
  fieldName: string;
  /** /SubFilter value: adbe.pkcs7.detached, ETSI.CAdES.detached, ETSI.RFC3161, ... */
  subFilter: string;
  /** CN (or first available DN component) of the signer cert. */
  signerName: string | null;
  /** Signing time. Prefers the CMS signed attribute; falls back to /M. ISO string. */
  signedAt: string | null;
  /** /Reason from the signature dict, if present. */
  reason?: string;
  /** /Location from the signature dict, if present. */
  location?: string;
  /** Integrity verdict — see SignatureIntegrityStatus for semantics. */
  integrity: SignatureIntegrityStatus;
  /** True if this signature includes a DocMDP /TransformParams entry — i.e.
   * it's a certification signature, not a plain approval signature. */
  isCertification: boolean;
}

export interface InspectSignaturesResult {
  signatures: ExistingSignatureInfo[];
}
